server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#    #指建立连接所用的时间（好像没什么用）
#    eureka-server-read-timeout-seconds: 1
#    #指建立连接后从服务器读取到可用资源所用时间（好像没什么用）
#    eureka-server-connect-timeout-seconds: 1
  instance:
    instance-id: feignorder80
    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    #lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    #lease-expiration-duration-in-seconds: 2

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.xiaoxi.cloud.service.PaymentFeignService: debug